In [1]:
pip install numpy 

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [5]:
arr = np.array([5, 6 , 7, 8 ])
arr

array([5, 6, 7, 8])

array(5)

In [28]:
arr_two = np.array([[5,6,7],[8,9,10]])
arr_two

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [14]:
arr = np.array([[[1,4,7],[2,5,8]],[[1,5,7],[3,5,9]]])
arr

array([[[1, 4, 7],
        [2, 5, 8]],

       [[1, 5, 7],
        [3, 5, 9]]])

In [15]:
arr.ndim

3

In [23]:
arr1= np.array([1,2,3,4,], ndmin=32)
arr1

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2,
                                      3, 4]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [24]:
arr[1,1]

array([3, 5, 9])

In [25]:
arr.shep

AttributeError: 'numpy.ndarray' object has no attribute 'shep'

In [29]:
arr_two.view

<function ndarray.view>

In [30]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr.shape

(9,)

In [32]:
new = arr.reshape(3,4)
new

ValueError: cannot reshape array of size 9 into shape (3,4)

In [ ]:
ar